### ISSUE TITLE
1.6 update

### ISSUE THREAD

**Issue by KariArisu** [Bpendragon/ForagePointers#1]
The new update broke this mod.

**Comment by Bpendragon** [comment]
In what ways? What exactly is the error shown in the smapi log?

My preliminary testing a while back seemed ok, and I was much more focused on Greenhouse Sprinklers. 

Honestly I may or may not be updating this for 1.6, depends on how much work it is, given that it directly interferes with other mods at times.

**Comment by terrulin** [comment]
I personally did not get any errors. But the pointers do not display either.

**Comment by Bpendragon** [comment]
Fair enough. I'll do some light debugging later if I have time. I'm not gonna promise anything, but I'll at least try to take a look.

**Comment by terrulin** [comment]
This is why I shouldnt do things in the middle of the night. I totally missed the beginning where this happened:
[SMAPI]    Skipped mods
[SMAPI]    --------------------------------------------------
[SMAPI]       These mods could not be added to your game.

[SMAPI]       - Forage Pointers 1.0.0 because it's no longer compatible. Please check for a new version at https://smapi.io/mods

I tried adjusting the manifest, but nothing seemed to help. Perhaps it just needs to be recompiled?

**Comment by Bpendragon** [comment]
Ok ill take a look in the next couple days

**Comment by terrulin** [comment]
People appreciate everything you did. Everything appears to be working perfectly.
